#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Satoshi Nemoto miraiprj3104@icloud.com
# SPDX-License-Identifier: BSD-3-Clause

import sys

money_time = sys.stdin.readline().split()
wage=float(money_time[0])
worktime=float(money_time[1])
if wage >= 1076:

    money = (int(52) * worktime)
    money = (money * wage)
    money = (money/float(10000))
    if money > 103:
        print("103万の壁突破")
    print("アルバイト年収は{}万円です".format(money))
else:
    print("千葉県の最低賃金を下回っています")
